<footer class="footer bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p class="copyright font-alt">&copy; 2017&nbsp;<a href="index.html">Robogals Melbourne</a>, All Rights Reserved</p>
      </div>
      <div class="col-sm-6">
        <div class="footer-social-links"><a href="https://www.facebook.com/RobogalsMelb/"><i class="fa fa-facebook"></i></a><a href="https://twitter.com/robogalsmelb/"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/robogalsmelb/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>