<div class="page-loader">
  <div class="loader">Loading...</div>
</div>
<nav class="navbar navbar-custom navbar-fixed-top navbar-transparent" role="navigation">
  <div class="container">
    <div class="navbar-header v-center-navbar-img">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="index.html"><img src="assets/images/robogals-melbourne-dark.png" width="30%" height="30%"></a>
    </div>
    <div class="collapse navbar-collapse" id="custom-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown"><a href='index.html'>Home</a>
        <li class="dropdown"><a href='about.html'>About Us</a>
        <li class="dropdown"><a href='resources.html'>Resources</a>
        <li class="dropdown"><a href='volunteer.html'>Volunteer</a>
        <li class="dropdown"><a href='partners.html'>Partners</a>
        <li class="dropdown"><a href='team.html'>Team</a>
        <li class="dropdown"><a href='contact.html'>Contact</a>
      </ul>
    </div>
  </div>
</nav>