<div class="page-loader">
  <div class="loader">Loading...</div>
</div>
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header v-center-navbar-img">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="index.html"><img src="assets/images/robogals-melbourne-dark.png" width="30%" height="30%"></a>
    </div>
    <div class="collapse navbar-collapse" id="custom-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown"><a href='index.php'>Home</a>
        <li class="dropdown"><a href='about.php'>About Us</a>
        <li class="dropdown"><a href='resources.php'>Resources</a>
        <li class="dropdown"><a href='volunteer.php'>Volunteer</a>
        <li class="dropdown"><a href='partners.php'>Partners</a>
        <li class="dropdown"><a href='team.php'>Team</a>
        <li class="dropdown"><a href='contact.php'>Contact</a>
      </ul>
    </div>
  </div>
</nav>